WITH 
SGA_TARGET_INST AS (select INST_ID,round(value/1073741824,1) SGA_TARGET_GB FROM gv$parameter WHERE name='sga_target' )   
,DB_BLOCK_SIZE_INST AS ( SELECT INST_ID,value db_block_size FROM gv$parameter WHERE name = 'db_block_size' )
,DATA AS ( SELECT SGA_INST.INST_ID ,SGA_TARGET_GB,round(sum(OBJ_INST.NUMBER_OF_BLOCKS*DB_BLOCK_SIZE/1073741824),1) BUFFER_CACHE_USED_GB
            FROM        SGA_TARGET_INST     SGA_INST
            INNER JOIN  DB_BLOCK_SIZE_INST  DB_BLOCK ON ( DB_BLOCK.INST_ID = SGA_INST.INST_ID ) 
            INNER JOIN ( SELECT GVBH.INST_ID,object_name, COUNT(*) number_of_blocks 
                         FROM DBA_OBJECTS         OBJ  
                         INNER JOIN GV$BH         GVBH ON ( GVBH.OBJD  = OBJ.DATA_OBJECT_ID ) 
                         WHERE OBJ.OWNER !=  'SYS'
                         GROUP BY GVBH.INST_ID,obj.object_Name
                      ) OBJ_INST ON ( OBJ_INST.INST_ID = SGA_INST.INST_ID )
             GROUP BY  SGA_INST.INST_ID,SGA_TARGET_GB       
)
,POOL_USED_GB        AS (select INST_ID,round(sum(bytes/1073741824),1) GB FROM gv$sgastat WHERE pool like '%pool%' GROUP BY INST_ID) 
,SHARED_POOL_GB      AS (select INST_ID,round(sum(bytes/1073741824),1)      GB FROM gv$sgainfo WHERE name='Shared Pool Size' GROUP BY INST_ID) 
,SHARED_POOL_USED_GB AS (select INST_ID,round(sum(bytes/1073741824),1) GB FROM gv$sgastat WHERE pool ='shared pool' and name<>'free memory' GROUP BY INST_ID) 
,BUFFER_CACHE_GB     AS (select INST_ID,round(sum(bytes/1073741824),1)      GB FROM gv$sgastat WHERE name = 'buffer_cache' GROUP BY INST_ID) 
,CALCUL AS (
    SELECT DATA.INST_ID, DATA.SGA_TARGET_GB ,DATA.BUFFER_CACHE_USED_GB
    ,POOL_USED_GB.GB       POOL_USED_GB  
    ,SHARED_POOL_GB.GB      SHARED_POOL_GB
    ,SHARED_POOL_USED_GB.GB SHARED_POOL_USED_GB
    ,BUFFER_CACHE_GB.GB     BUFFER_CACHE_GB
    FROM DATA
    INNER JOIN POOL_USED_GB          ON ( POOL_USED_GB.INST_ID         = DATA.INST_ID ) 
    INNER JOIN SHARED_POOL_GB        ON ( SHARED_POOL_GB.INST_ID       = DATA.INST_ID ) 
    INNER JOIN SHARED_POOL_USED_GB   ON ( SHARED_POOL_USED_GB.INST_ID  = DATA.INST_ID ) 
    INNER JOIN BUFFER_CACHE_GB       ON ( BUFFER_CACHE_GB.INST_ID      = DATA.INST_ID ) 
)
SELECT
  INST_ID,SGA_TARGET_GB, POOL_USED_GB, SHARED_POOL_GB, SHARED_POOL_USED_GB, BUFFER_CACHE_GB, BUFFER_CACHE_USED_GB
  ,(SGA_TARGET_GB-BUFFER_CACHE_USED_GB-SHARED_POOL_USED_GB) SGA_FREE_GB
  ,round(((SGA_TARGET_GB-BUFFER_CACHE_USED_GB-SHARED_POOL_USED_GB)*100/SGA_TARGET_GB),1) SGA_FREE_PERCENT
FROM CALCUL  
ORDER BY INST_ID
;